### ISSUE TITLE
API Update Timing

### ISSUE THREAD

**Issue by Yukkitio** [leonlarsson/the-finals-api#1]
HI wanted to know how often the API is updated ( The Finals Leader board) Like every 30 min ? After each fetch ?
Or it's "random" from Embark ?

**Comment by leonlarsson** [comment]
Hey. I am unsure how often Embark updates the leaderboard. I think it's on a pretty low interval like 30 minutes though.

**Comment by Yukkitio** [comment]
So 0H00 , 0H30, 1H , 1H30 and so on ?
( to know when to update value and show a timier for it (like update in XXX ) )

**Comment by leonlarsson** [comment]
I don't know. You can fetch often and always have the latest data.

**Comment by Yukkitio** [comment]
Okay np, can you explain what mean some JSON  abreviations ?
EX : 
{
"r":1,
"name":"Gigz#6349",
"ri":20,
"p":0,
"ori":20,
"or":2,
"op":0,
"c":0,
"steam":"Gigz",
"xbox":"",
"psn":"T1-Gigz"
}

What mean ri ? p ? ori ? or ? op ? c ? Thanks :D

**Comment by leonlarsson** [comment]
- `ri` is rank index that maps to a league. More info here: https://github.com/leonlarsson/the-finals-api/blob/main/src/utils/leagueNumberToName.ts
- `p` no clue
- `ori` is old rank index (24 hours ago)
- `or` is old rank (24 hours ago)
- `op` is probably old `p`
- `c` is likely cashouts, but this isn't used

**Comment by Yukkitio** [comment]
Hi back, wanted to know to how in S1 you manage to get a graph ? Did in S1 there where a table in the API or did you make a Custom BDD who register every 24h the rank ?

Thanks :)

**Comment by leonlarsson** [comment]
Do you mean the personal player history?

That was provided by a third party API that had now been disabled. https://github.com/leonlarsson/the-finals-leaderboard/pull/11
