### ISSUE TITLE
"live" version invalid

### ISSUE THREAD

**Issue by skyfr0676** [leonlarsson/the-finals-api#2]
https://api.the-finals-leaderboard.com/v1/leaderboard/live/crossplay?name=Sky%231678

output:
{
  "error": "Leaderboard version 'live' is not a valid version. Valid versions: cb1, closedbeta1, cb2, closedbeta2, ob, openbeta, s1, season1, s2, season2. Example: /v1/leaderboard/cb1"
}

**Comment by leonlarsson** [comment]
Apologies. This has been fixed now

**Comment by leonlarsson** [comment]
By the way, "live" will be used for Season 3 in the coming days (assuming there is a good way to get the data). I recommend to use one of the other static version names
