### ISSUE TITLE
error on fetching leaderboard filtered by name

### ISSUE THREAD

**Issue by skyfr0676** [leonlarsson/the-finals-api#3]
`{"error":"An error occurred while fetching the leaderboard: s4"}`

using parameter "name"

**Comment by skyfr0676** [comment]
example 1: https://api.the-finals-leaderboard.com/v1/leaderboard/s4/crossplay?count=true&name=ttv
example 2: https://api.the-finals-leaderboard.com/v1/leaderboard/s4/crossplay?name=Sky%231678

error: 500

**Comment by leonlarsson** [comment]
Having a look now

**Comment by skyfr0676** [comment]
thank you !

**Comment by skyfr0676** [comment]
Thank you for solving the issue :D

**Comment by leonlarsson** [comment]
A fix has been deployed.
Root cause: A single entry in the S4 leaderboard had their username set as 0 (number) instead of a string. Perhaps because they were banned or something.
```json
{"1":4059,"2":57070,"3":0,"4":11,"5":25114,"6":"ඞ ⁧ AK","7":0,"8":0}
```
I will fall back to returning "Unknown#0000"
